routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('OPD', 'OPDController');

Route::resource('hmis', 'HmisController')->middleware('auth');

app/Hmis.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Hmis extends Model
{
    protected $fillable = [
        'unit_tb_number',
        'hsb_tb_number',
        'district_tb_number',
        'contact_phone_number',
        'relationship_of_contact_person',
        'is_patient_health_worker',
        'cadre_of_health_worker',
        'date_treatment_started',
        'regime',
        'type_pf_patient',
        'specific_regimen',
        'transfer_in_form',
    ];
}

app/Http/Controllers/HmisController.php
<?php

namespace App\Http\Controllers;

use App\Hmis;
use Illuminate\Http\Request;

class HmisController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $hmis_records = Hmis::all();

        return view('hmis.index', compact('hmis_records'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('hmis.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Hmis::create($request->all());
        $request->session()->flash('success', 'Recorded Added Successfully');
        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $hmis = Hmis::where('id', $id)->first();

        return view('hmis.show', compact('hmis'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/hmis/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    @if (session('success'))
    <div class="alert alert-success">{{ session('success') }}</div>
    @endif
    <div class="card">
        <div class="card-header">
            <div class="float-left">HMIS 096A Health Unit TB Form</div>
            <div class="float-right">
                <a class="btn btn-success" href="{{ route('hmis.index') }}">Back to Record List</a>
            </div>
        </div>
        <div class="card-body">
            <form action="{{ route('hmis.store') }}" method="POST">
                @csrf
                <div class="my-2">
                    <div class="row">
                        <div class="col-md-4">
                            <label for="unit_tb">Unit TB Number</label>
                            <input name="unit_tb_number" type="text" class="form-control">
                        </div>
                        <div class="col-md-4">
                            <label for="hsb_tb_no">HSB TB No</label>
                            <input name="hsb_tb_number" type="text" class="form-control">
                        </div>
                        <div class="col-md-4">
                            <label for="district_tb_number">District TB Number</label>
                            <input name="district_tb_number" type="text" class="form-control">
                        </div>
                    </div>
                </div>
                <div class="my-2">
                    <div class="row">
                        <div class="col-md-4">
                            <label for="contact_phone_number">Contact Phone Number</label>
                            <input name="contact_phone_number" type="text" class="form-control">
                        </div>
                        <div class="col-md-4">
                            <label for="relationship_of_contact_person">Relationship of Contact Person</label>
                            <input name="relationship_of_contact_person" type="text" class="form-control">
                        </div>
                        <div class="col-md-4">
                            <label for="patient_status">Is patient a Health Worker</label>
                            <div class="mt-2">
                                <p class="float-left"><input name="is_patient_health_worker" type="radio"> Yes</p>
                                <p class="float-right"><input name="is_patient_health_worker" type="radio"> No</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="my-2">
                    <div class="row">
                        <div class="col-md-4">
                            <label for="cadre_of_health_worker">Cadre of Health Worker</label>
                            <input name="cadre_of_health_worker" type="text" class="form-control">
                        </div>
                        <div class="col-md-4">
                            <label for="date_treatment_started">Date Treatment Started</label>
                            <input name="date_treatment_started" type="date" class="form-control">
                        </div>
                        <div class="col-md-4">
                            <label for="regime">Regime</label>
                            <input name="regime" type="text" class="form-control">
                        </div>
                    </div>
                </div>
                <div class="my-2">
                    <div class="row">
                        <div class="col-md-4">
                            <label for="type_of_patient">Type of Patient</label>
                            <select name="type_pf_patient" class="form-control">
                                <option value="New">New</option>
                                <option value="Old">Old</option>
                            </select>
                        </div>
                        <div class="col-md-4">
                            <label for="specify_regimen">Specify Regimen</label>
                            <input name="specific_regimen" type="text" class="form-control">
                        </div>
                        <div class="col-md-4">
                            <label for="transfer_in_from">Transfer in from</label>
                            <input name="transfer_in_form" type="text" class="form-control">
                        </div>
                    </div>
                </div>
                <div class="my-4">
                    <div class="row">
                        <div class="col-md-4">
                            <button type="submit" class="btn btn-secondary">Submit</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</div>
@endsection

resources/views/hmis/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    @if (session('success'))
    <div class="alert alert-danger">{{ session('success') }}</div>
    @endif
    <div class="card">
        <div class="card-header">
            <div class="float-left">HMIS 096A Health Unit TB Form</div>
            <div class="float-right">
                <a class="btn btn-primary" href="{{ route('hmis.create') }}">Add Record</a>
            </div>
        </div>
        <div class="card-body">
            <table class="table table-striped">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Unit TB Number</th>
                        <th>HSD TB Number</th>
                        <th>District TB Number</th>
                        <th>Contact Phone</th>
                        <th>Action</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @forelse ($hmis_records as $hmis)
                    <tr>
                        <td>{{ $hmis->id }}</td>
                        <td>{{ $hmis->unit_tb_number }}</td>
                        <td>{{ $hmis->hsb_tb_number }}</td>
                        <td>{{ $hmis->district_tb_number }}</td>
                        <td>{{ $hmis->contact_phone_number }}</td>
                        <td><a class="btn btn-primary btn-sm" href="{{ route('hmis.show', $hmis->id) }}">Show Detail</a>
                        </td>
                        <td><a class="btn btn-danger btn-sm" href="{{ route('hmis.destroy', $hmis->id) }}">Delete</a>
                        </td>
                    </tr>
                    @empty
                    <tr>
                        <td>No Record Found</td>
                    </tr>
                    @endforelse
                </tbody>
            </table>
        </div>
    </div>
</div>
@endsection

resources/views/hmis/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    @if (session('success'))
    <div class="alert alert-danger">{{ session('success') }}</div>
    @endif
    <div class="card">
        <div class="card-header">
            <div class="float-left">Show Details</div>
        </div>
        <div class="card-body">
            <p></p>
        </div>
    </div>
</div>
@endsection